### PR TITLE
BODATA-476 Update NodeJS version/FIPS

### PR DESCRIPTION
**Pull request by ayohrling**
This PR updates the packaged version of NodeJS to 4.2.2. This also adds support to build with FIPS support via setting a macro. 

To build with FIPS, the Jenkins build job has been updated to setup the openssl-fips library in the mock chroots and to set the fips macro option for the specfile.

@immuta/devops 
@immuta/developers

### CODE REVIEW

**Comment by ayohrling** [comment]
Closing to reopen PR to retest. Needed to export variables in the Jenkins job.

**Comment by ayohrling** [comment]
Reopening.

**Comment by ayohrling** [comment]
Added envInject plugin

**Comment by ayohrling** [comment]
Because I suck and didn't realize quotes couldn't be in the envInject.

**Comment by ayohrling** [comment]
Ok, I think I fixed all the build issues in Jenkins and have tested manually, closing and re-opening one last time.

**Comment by ayohrling** [comment]
Annnd the slave disk was full this time...

**Comment by barryhammen** [comment]
:+1:

**Comment by ayohrling** [comment]
This is on hold while I troubleshoot an issue I'm having with npm install failing out due to FIPS...I have reached out to their support list and am still fumbling with it in the meantime.

**Comment by ayohrling** [comment]
Ok, I'm closing this PR. I found the culprits. write-file-atomic and fs-write-stream-atomic modules hardcode md5 digest usage when creating temporary filenames. I have submitted tickets against the projects, but the easiest way is for me to create patches against the files to move them to sha1 and include those patches as sources for the RPM build...

**Pull request closed without merging**
